//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HttpNodeConfigMethod.
const (
	DELETE HttpNodeConfigMethod = "DELETE"
	GET    HttpNodeConfigMethod = "GET"
	PATCH  HttpNodeConfigMethod = "PATCH"
	POST   HttpNodeConfigMethod = "POST"
	PUT    HttpNodeConfigMethod = "PUT"
)

// Valid indicates whether the value is a known member of the HttpNodeConfigMethod enum.
func (e HttpNodeConfigMethod) Valid() bool {
	switch e {
	case DELETE:
		return true
	case GET:
		return true
	case PATCH:
		return true
	case POST:
		return true
	case PUT:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	Cancelled RunStatus = "cancelled"
	Completed RunStatus = "completed"
	Failed    RunStatus = "failed"
	Pending   RunStatus = "pending"
	Running   RunStatus = "running"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// ActivityOptions Per-node Temporal ActivityOptions overriding GraphWorkflow defaults
// (`startToCloseTimeout` = 30s, `maximumAttempts` = 1). Omitted fields
// keep engine defaults. Only valid on activity-backed node types
// (`KindActivity`); rejected on workflow-native nodes (start, delay,
// condition, wait, childWorkflow).
type ActivityOptions struct {
	// HeartbeatTimeoutSeconds Heartbeat timeout for long-running activities.
	HeartbeatTimeoutSeconds *float64 `json:"heartbeatTimeoutSeconds,omitempty"`

	// RetryPolicy Temporal activity retry policy. Engine default is maximumAttempts: 1
	// (no retries). Raising attempts for side-effecting nodes (e.g. HTTP POST)
	// is the caller's responsibility — only do so for idempotent work.
	// Temporal treats maximumAttempts 0 as unlimited; this API rejects 0 so
	// callers must set an explicit bound.
	RetryPolicy *RetryPolicy `json:"retryPolicy,omitempty"`

	// ScheduleToCloseTimeoutSeconds Max time from schedule to completion across all attempts
	// (Temporal ScheduleToCloseTimeout).
	ScheduleToCloseTimeoutSeconds *float64 `json:"scheduleToCloseTimeoutSeconds,omitempty"`

	// StartToCloseTimeoutSeconds Max time for a single activity attempt (Temporal StartToCloseTimeout).
	// Note: the built-in HTTP activity still caps its own HTTP client at
	// 20s; raising this above 20s does not lengthen that client timeout.
	StartToCloseTimeoutSeconds *float64 `json:"startToCloseTimeoutSeconds,omitempty"`
}

// ChildWorkflowNodeConfig Run a nested graph as a Temporal child workflow (temflowral.graph) and
// wait for its result. The parent node fails if the child fails.
type ChildWorkflowNodeConfig struct {
	// Graph Inline graph executed as a Temporal child workflow. Same node/edge
	// shape as a top-level graph, without persisted id/timestamps. Nested
	// graphs must not contain childWorkflow nodes (nesting depth is capped
	// at one for now).
	Graph NestedGraph `json:"graph"`

	// Input Optional payload for the child's GraphWorkflowInput. When omitted,
	// the first active predecessor's value is used (or an empty object).
	Input *map[string]interface{} `json:"input,omitempty"`
}

// ConditionNodeConfig defines model for ConditionNodeConfig.
type ConditionNodeConfig struct {
	// Equals Expected value compared with JSON equality against value[field].
	// Missing fields do not match (the false branch is taken).
	Equals interface{} `json:"equals"`

	// Field Top-level key in the first active predecessor's value map. Nested
	// paths and expression languages are intentionally unsupported to
	// avoid template/injection risks.
	Field string `json:"field"`
}

// CreateGraphRequest defines model for CreateGraphRequest.
type CreateGraphRequest struct {
	Edges []Edge  `json:"edges"`
	Name  *string `json:"name,omitempty"`
	Nodes []Node  `json:"nodes"`
}

// DelayNodeConfig defines model for DelayNodeConfig.
type DelayNodeConfig struct {
	// Seconds Delay duration in seconds (0 to 604800 = 7 days) before the workflow
	// continues. Implemented with a durable Temporal timer, so the wait
	// survives worker restarts.
	Seconds float64 `json:"seconds"`
}

// Edge defines model for Edge.
type Edge struct {
	// Id Unique edge ID within the graph
	Id string `json:"id"`

	// Source Source node ID
	Source string `json:"source"`

	// SourceHandle Source handle ID selecting which output of a multi-output node this
	// edge belongs to. Must match a handle advertised by the source
	// node's type (`NodeType.outputHandles` or handles derived via
	// `NodeType.outputHandlesFromConfig`). Built-in condition handles are
	// "true" and "false"; wait handles are "received" and "timedOut".
	SourceHandle *string `json:"sourceHandle,omitempty"`

	// Target Target node ID
	Target string `json:"target"`

	// TargetHandle Target handle ID
	TargetHandle *string `json:"targetHandle,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable error code
	Code *string `json:"code,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// Graph defines model for Graph.
type Graph struct {
	CreatedAt time.Time          `json:"createdAt"`
	Edges     []Edge             `json:"edges"`
	Id        openapi_types.UUID `json:"id"`
	Name      *string            `json:"name,omitempty"`
	Nodes     []Node             `json:"nodes"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// HttpNodeConfig defines model for HttpNodeConfig.
type HttpNodeConfig struct {
	// Body Optional request body, limited to 1 MiB. May contain
	// `{{ nodes.<nodeId>.output.<path> }}` templates resolved at run time.
	// After resolution the body is still size-capped at 1 MiB.
	Body *string `json:"body,omitempty"`

	// Headers Optional request headers. Values may use the same
	// `{{ nodes.<nodeId>.output.<path> }}` templates as url/body; the
	// fully rendered header set is revalidated (hop-by-hop and
	// transport-controlled headers remain rejected).
	Headers *map[string]string `json:"headers,omitempty"`

	// Method HTTP method. Activity retries are disabled to avoid replaying side effects.
	Method HttpNodeConfigMethod `json:"method"`

	// Url Absolute HTTP(S) URL, or a string containing
	// `{{ nodes.<nodeId>.output.<path> }}` templates resolved at run time
	// from active predecessor outputs. After resolution the URL must be
	// absolute HTTP(S) and pass the same allowlist/SSRF checks as a
	// concrete URL. Destinations are denied by default: the worker only
	// permits hostnames listed in HTTP_ALLOWED_HOSTS (exact hostnames,
	// no schemes/ports/wildcards) and rejects private, loopback,
	// link-local, multicast, and unspecified destination addresses. See
	// SECURITY.md for timeouts, size limits, redirect policy, and
	// templating rules.
	Url string `json:"url"`
}

// HttpNodeConfigMethod HTTP method. Activity retries are disabled to avoid replaying side effects.
type HttpNodeConfigMethod string

// NestedGraph Inline graph executed as a Temporal child workflow. Same node/edge
// shape as a top-level graph, without persisted id/timestamps. Nested
// graphs must not contain childWorkflow nodes (nesting depth is capped
// at one for now).
type NestedGraph struct {
	Edges []Edge `json:"edges"`
	Nodes []Node `json:"nodes"`
}

// Node defines model for Node.
type Node struct {
	// ActivityOptions Per-node Temporal ActivityOptions overriding GraphWorkflow defaults
	// (`startToCloseTimeout` = 30s, `maximumAttempts` = 1). Omitted fields
	// keep engine defaults. Only valid on activity-backed node types
	// (`KindActivity`); rejected on workflow-native nodes (start, delay,
	// condition, wait, childWorkflow).
	ActivityOptions *ActivityOptions `json:"activityOptions,omitempty"`

	// Config Node-type-specific configuration. Validated against the node type's
	// configSchema from GET /node-types. HTTP nodes use HttpNodeConfig;
	// delay nodes use DelayNodeConfig; condition nodes use ConditionNodeConfig;
	// wait nodes use WaitNodeConfig; childWorkflow nodes use
	// ChildWorkflowNodeConfig.
	//
	// String leaves may contain `{{ nodes.<nodeId>.output.<path> }}`
	// templates resolved at run time from active predecessor outputs.
	// See SECURITY.md. Templates are not allowed in wait node config.
	Config *map[string]interface{} `json:"config,omitempty"`

	// Id Unique node ID within the graph (client-assigned)
	Id string `json:"id"`

	// Label Display label on the canvas
	Label    *string  `json:"label,omitempty"`
	Position Position `json:"position"`

	// TaskQueue Optional Temporal task queue for this node's activity. When omitted,
	// the activity uses the workflow's default task queue (the worker that
	// runs GraphWorkflow). Only valid on activity-backed node types
	// (`KindActivity`); rejected on workflow-native nodes (start, delay,
	// condition, wait, childWorkflow). Use a dedicated worker polling this
	// queue when the activity needs specialized capabilities (region,
	// hardware, licenses).
	TaskQueue *string `json:"taskQueue,omitempty"`

	// Type Node type identifier (matches NodeType.id)
	Type string `json:"type"`
}

// NodeOutputHandle defines model for NodeOutputHandle.
type NodeOutputHandle struct {
	// Id Handle ID referenced by Edge.sourceHandle
	Id string `json:"id"`

	// Label Optional human-readable label for the canvas
	Label *string `json:"label,omitempty"`
}

// NodeType defines model for NodeType.
type NodeType struct {
	// Category Grouping label for the palette (e.g. core, integration)
	Category *string `json:"category,omitempty"`

	// ConfigSchema JSON Schema describing valid Node.config for this type
	ConfigSchema map[string]interface{} `json:"configSchema"`
	Description  *string                `json:"description,omitempty"`

	// Id Node type identifier (referenced by Node.type)
	Id string `json:"id"`

	// Name Human-readable name for the palette
	Name string `json:"name"`

	// OutputHandles Fixed output handles when the set does not depend on config.
	// Omit or leave empty for a single unnamed default output.
	// Do not combine with outputHandlesFromConfig on the same type.
	OutputHandles *[]NodeOutputHandle `json:"outputHandles,omitempty"`

	// OutputHandlesFromConfig Derives output handle IDs from a field in Node.config at plan and edit
	// time. Use this when the handle set depends on configuration (for
	// example N branch keys → N handles). Supported values at `path`:
	// an array of strings; an array of objects with an `id` string field;
	// or an object whose keys become handle IDs.
	OutputHandlesFromConfig *OutputHandlesFromConfig `json:"outputHandlesFromConfig,omitempty"`
}

// NodeTypeList defines model for NodeTypeList.
type NodeTypeList struct {
	NodeTypes []NodeType `json:"nodeTypes"`
}

// OutputHandlesFromConfig Derives output handle IDs from a field in Node.config at plan and edit
// time. Use this when the handle set depends on configuration (for
// example N branch keys → N handles). Supported values at `path`:
// an array of strings; an array of objects with an `id` string field;
// or an object whose keys become handle IDs.
type OutputHandlesFromConfig struct {
	// Path Dot-separated path into Node.config (e.g. "branches")
	Path string `json:"path"`
}

// Position defines model for Position.
type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

// RetryPolicy Temporal activity retry policy. Engine default is maximumAttempts: 1
// (no retries). Raising attempts for side-effecting nodes (e.g. HTTP POST)
// is the caller's responsibility — only do so for idempotent work.
// Temporal treats maximumAttempts 0 as unlimited; this API rejects 0 so
// callers must set an explicit bound.
type RetryPolicy struct {
	// BackoffCoefficient Multiplier applied after each retry (Temporal BackoffCoefficient).
	BackoffCoefficient *float64 `json:"backoffCoefficient,omitempty"`

	// InitialIntervalSeconds Delay before the first retry (Temporal InitialInterval).
	InitialIntervalSeconds *float64 `json:"initialIntervalSeconds,omitempty"`

	// MaximumAttempts Maximum activity attempts including the first. 1 disables retries
	// (engine default).
	MaximumAttempts int `json:"maximumAttempts"`

	// MaximumIntervalSeconds Cap on the delay between retries (Temporal MaximumInterval).
	MaximumIntervalSeconds *float64 `json:"maximumIntervalSeconds,omitempty"`

	// NonRetryableErrorTypes Temporal error type names that must not be retried.
	NonRetryableErrorTypes *[]string `json:"nonRetryableErrorTypes,omitempty"`
}

// Run defines model for Run.
type Run struct {
	// CompletedAt Set when status is terminal (completed, failed, cancelled)
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// Error Error message when status is failed or cancelled
	Error   *string            `json:"error,omitempty"`
	GraphId openapi_types.UUID `json:"graphId"`
	Id      openapi_types.UUID `json:"id"`

	// Result Workflow output when status is completed. Shape:
	// `{ "nodes": [ { "nodeId": "<id>", "value": { ... } } ] }`.
	// `value` is node-type-specific (start echoes the run input; http
	// includes statusCode/body; delay includes seconds; condition
	// includes matched/branch; wait includes signal/timedOut/branch and
	// optional payload; childWorkflow includes type/nodes from the child
	// GraphWorkflowResult; noop echoes type/inputs).
	Result    *map[string]interface{} `json:"result,omitempty"`
	StartedAt time.Time               `json:"startedAt"`

	// Status Current lifecycle state of a workflow run
	Status RunStatus `json:"status"`
}

// RunStatus Current lifecycle state of a workflow run
type RunStatus string

// SignalRunRequest defines model for SignalRunRequest.
type SignalRunRequest struct {
	// Payload Optional JSON value delivered with the Temporal signal and stored on
	// the wait node's result when the signal wins the timeout race.
	Payload *interface{} `json:"payload,omitempty"`

	// Signal Must match the `WaitNodeConfig.signal` of the wait node the run is
	// currently blocked on.
	Signal string `json:"signal"`
}

// SignalRunResponse defines model for SignalRunResponse.
type SignalRunResponse struct {
	AcceptedAt time.Time          `json:"acceptedAt"`
	RunId      openapi_types.UUID `json:"runId"`
	Signal     string             `json:"signal"`
}

// StartRunRequest defines model for StartRunRequest.
type StartRunRequest struct {
	// IdempotencyKey Optional caller-supplied key scoped to the graph. Repeating
	// StartGraphRun with the same key returns the first run instead of
	// starting a duplicate Temporal workflow. Omit for fire-and-forget
	// starts that always create a new run.
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`

	// Input Optional input payload passed to the workflow
	Input *map[string]interface{} `json:"input,omitempty"`
}

// WaitNodeConfig defines model for WaitNodeConfig.
type WaitNodeConfig struct {
	// Signal Temporal signal name this node waits on. Deliver the same name via
	// `POST /runs/{runId}/signal`. Letters, digits, `.`, `_`, and `-` only.
	Signal string `json:"signal"`

	// TimeoutSeconds Max wait in seconds (0 to 604800 = 7 days) before taking the
	// timedOut branch. Implemented with a durable Temporal timer racing
	// the signal channel, so the wait survives worker restarts.
	TimeoutSeconds float64 `json:"timeoutSeconds"`
}

// GraphId defines model for GraphId.
type GraphId = openapi_types.UUID

// RunId defines model for RunId.
type RunId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateGraphJSONRequestBody defines body for CreateGraph for application/json ContentType.
type CreateGraphJSONRequestBody = CreateGraphRequest

// StartGraphRunJSONRequestBody defines body for StartGraphRun for application/json ContentType.
type StartGraphRunJSONRequestBody = StartRunRequest

// SignalRunJSONRequestBody defines body for SignalRun for application/json ContentType.
type SignalRunJSONRequestBody = SignalRunRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateGraph Create a graph
	// (POST /graphs)
	CreateGraph(w http.ResponseWriter, r *http.Request)
	// GetGraph Fetch a graph by ID
	// (GET /graphs/{graphId})
	GetGraph(w http.ResponseWriter, r *http.Request, graphId GraphId)
	// StartGraphRun Start a workflow run from a graph
	// (POST /graphs/{graphId}/run)
	StartGraphRun(w http.ResponseWriter, r *http.Request, graphId GraphId)
	// ListNodeTypes List available node types
	// (GET /node-types)
	ListNodeTypes(w http.ResponseWriter, r *http.Request)
	// GetRun Poll run status and result
	// (GET /runs/{runId})
	GetRun(w http.ResponseWriter, r *http.Request, runId RunId)
	// SignalRun Deliver a Temporal signal to a running workflow
	// (POST /runs/{runId}/signal)
	SignalRun(w http.ResponseWriter, r *http.Request, runId RunId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateGraph operation middleware
func (siw *ServerInterfaceWrapper) CreateGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "graphId" -------------
	var graphId GraphId

	err = runtime.BindStyledParameterWithOptions("simple", "graphId", r.PathValue("graphId"), &graphId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "graphId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r, graphId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartGraphRun operation middleware
func (siw *ServerInterfaceWrapper) StartGraphRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "graphId" -------------
	var graphId GraphId

	err = runtime.BindStyledParameterWithOptions("simple", "graphId", r.PathValue("graphId"), &graphId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "graphId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartGraphRun(w, r, graphId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodeTypes operation middleware
func (siw *ServerInterfaceWrapper) ListNodeTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodeTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignalRun operation middleware
func (siw *ServerInterfaceWrapper) SignalRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignalRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/graphs", wrapper.CreateGraph)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/graphs/{graphId}", wrapper.GetGraph)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/graphs/{graphId}/run", wrapper.StartGraphRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{runId}", wrapper.GetRun)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/runs/{runId}/signal", wrapper.SignalRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/node-types", wrapper.ListNodeTypes)

	return m
}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type CreateGraphRequestObject struct {
	Body *CreateGraphJSONRequestBody
}

type CreateGraphResponseObject interface {
	VisitCreateGraphResponse(w http.ResponseWriter) error
}

type CreateGraph201JSONResponse Graph

func (response CreateGraph201JSONResponse) VisitCreateGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGraph400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateGraph400JSONResponse) VisitCreateGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGraph401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateGraph401JSONResponse) VisitCreateGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGraph500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateGraph500JSONResponse) VisitCreateGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraphRequestObject struct {
	GraphId GraphId `json:"graphId"`
}

type GetGraphResponseObject interface {
	VisitGetGraphResponse(w http.ResponseWriter) error
}

type GetGraph200JSONResponse Graph

func (response GetGraph200JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraph401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetGraph401JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraph404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGraph404JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraph500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetGraph500JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRunRequestObject struct {
	GraphId GraphId `json:"graphId"`
	Body    *StartGraphRunJSONRequestBody
}

type StartGraphRunResponseObject interface {
	VisitStartGraphRunResponse(w http.ResponseWriter) error
}

type StartGraphRun202JSONResponse Run

func (response StartGraphRun202JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRun400JSONResponse struct{ BadRequestJSONResponse }

func (response StartGraphRun400JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRun401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StartGraphRun401JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRun404JSONResponse struct{ NotFoundJSONResponse }

func (response StartGraphRun404JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRun409JSONResponse Error

func (response StartGraphRun409JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRun500JSONResponse struct{ InternalErrorJSONResponse }

func (response StartGraphRun500JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListNodeTypesRequestObject struct {
}

type ListNodeTypesResponseObject interface {
	VisitListNodeTypesResponse(w http.ResponseWriter) error
}

type ListNodeTypes200JSONResponse NodeTypeList

func (response ListNodeTypes200JSONResponse) VisitListNodeTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNodeTypes400JSONResponse struct{ BadRequestJSONResponse }

func (response ListNodeTypes400JSONResponse) VisitListNodeTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListNodeTypes401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListNodeTypes401JSONResponse) VisitListNodeTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListNodeTypes500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListNodeTypes500JSONResponse) VisitListNodeTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRunRequestObject struct {
	RunId RunId `json:"runId"`
}

type GetRunResponseObject interface {
	VisitGetRunResponse(w http.ResponseWriter) error
}

type GetRun200JSONResponse Run

func (response GetRun200JSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRun401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetRun401JSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRun404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRun404JSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRun500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetRun500JSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SignalRunRequestObject struct {
	RunId RunId `json:"runId"`
	Body  *SignalRunJSONRequestBody
}

type SignalRunResponseObject interface {
	VisitSignalRunResponse(w http.ResponseWriter) error
}

type SignalRun202JSONResponse SignalRunResponse

func (response SignalRun202JSONResponse) VisitSignalRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type SignalRun400JSONResponse struct{ BadRequestJSONResponse }

func (response SignalRun400JSONResponse) VisitSignalRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SignalRun401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SignalRun401JSONResponse) VisitSignalRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SignalRun404JSONResponse struct{ NotFoundJSONResponse }

func (response SignalRun404JSONResponse) VisitSignalRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SignalRun409JSONResponse Error

func (response SignalRun409JSONResponse) VisitSignalRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SignalRun500JSONResponse struct{ InternalErrorJSONResponse }

func (response SignalRun500JSONResponse) VisitSignalRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateGraph Create a graph
	// (POST /graphs)
	CreateGraph(ctx context.Context, request CreateGraphRequestObject) (CreateGraphResponseObject, error)
	// GetGraph Fetch a graph by ID
	// (GET /graphs/{graphId})
	GetGraph(ctx context.Context, request GetGraphRequestObject) (GetGraphResponseObject, error)
	// StartGraphRun Start a workflow run from a graph
	// (POST /graphs/{graphId}/run)
	StartGraphRun(ctx context.Context, request StartGraphRunRequestObject) (StartGraphRunResponseObject, error)
	// ListNodeTypes List available node types
	// (GET /node-types)
	ListNodeTypes(ctx context.Context, request ListNodeTypesRequestObject) (ListNodeTypesResponseObject, error)
	// GetRun Poll run status and result
	// (GET /runs/{runId})
	GetRun(ctx context.Context, request GetRunRequestObject) (GetRunResponseObject, error)
	// SignalRun Deliver a Temporal signal to a running workflow
	// (POST /runs/{runId}/signal)
	SignalRun(ctx context.Context, request SignalRunRequestObject) (SignalRunResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateGraph operation middleware
func (sh *strictHandler) CreateGraph(w http.ResponseWriter, r *http.Request) {
	var request CreateGraphRequestObject

	var body CreateGraphJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGraph(ctx, request.(CreateGraphRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGraph")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGraphResponseObject); ok {
		if err := validResponse.VisitCreateGraphResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGraph operation middleware
func (sh *strictHandler) GetGraph(w http.ResponseWriter, r *http.Request, graphId GraphId) {
	var request GetGraphRequestObject

	request.GraphId = graphId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGraph(ctx, request.(GetGraphRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGraph")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGraphResponseObject); ok {
		if err := validResponse.VisitGetGraphResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartGraphRun operation middleware
func (sh *strictHandler) StartGraphRun(w http.ResponseWriter, r *http.Request, graphId GraphId) {
	var request StartGraphRunRequestObject

	request.GraphId = graphId

	var body StartGraphRunJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartGraphRun(ctx, request.(StartGraphRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartGraphRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartGraphRunResponseObject); ok {
		if err := validResponse.VisitStartGraphRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNodeTypes operation middleware
func (sh *strictHandler) ListNodeTypes(w http.ResponseWriter, r *http.Request) {
	var request ListNodeTypesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListNodeTypes(ctx, request.(ListNodeTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNodeTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListNodeTypesResponseObject); ok {
		if err := validResponse.VisitListNodeTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRun operation middleware
func (sh *strictHandler) GetRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	var request GetRunRequestObject

	request.RunId = runId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRun(ctx, request.(GetRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRunResponseObject); ok {
		if err := validResponse.VisitGetRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SignalRun operation middleware
func (sh *strictHandler) SignalRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	var request SignalRunRequestObject

	request.RunId = runId

	var body SignalRunJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SignalRun(ctx, request.(SignalRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignalRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SignalRunResponseObject); ok {
		if err := validResponse.VisitSignalRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
