//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for RunStatus.
const (
	Cancelled RunStatus = "cancelled"
	Completed RunStatus = "completed"
	Failed    RunStatus = "failed"
	Pending   RunStatus = "pending"
	Running   RunStatus = "running"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// CreateGraphRequest defines model for CreateGraphRequest.
type CreateGraphRequest struct {
	Edges []Edge  `json:"edges"`
	Name  *string `json:"name,omitempty"`
	Nodes []Node  `json:"nodes"`
}

// Edge defines model for Edge.
type Edge struct {
	// Id Unique edge ID within the graph
	Id string `json:"id"`

	// Source Source node ID
	Source string `json:"source"`

	// SourceHandle Source handle ID (for branching nodes)
	SourceHandle *string `json:"sourceHandle,omitempty"`

	// Target Target node ID
	Target string `json:"target"`

	// TargetHandle Target handle ID
	TargetHandle *string `json:"targetHandle,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable error code
	Code *string `json:"code,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// Graph defines model for Graph.
type Graph struct {
	CreatedAt time.Time          `json:"createdAt"`
	Edges     []Edge             `json:"edges"`
	Id        openapi_types.UUID `json:"id"`
	Name      *string            `json:"name,omitempty"`
	Nodes     []Node             `json:"nodes"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// Node defines model for Node.
type Node struct {
	// Config Node-type-specific configuration. Validated against the node type's
	// configSchema from GET /node-types.
	Config *map[string]interface{} `json:"config,omitempty"`

	// Id Unique node ID within the graph (client-assigned)
	Id string `json:"id"`

	// Label Display label on the canvas
	Label    *string  `json:"label,omitempty"`
	Position Position `json:"position"`

	// Type Node type identifier (matches NodeType.id)
	Type string `json:"type"`
}

// NodeType defines model for NodeType.
type NodeType struct {
	// Category Grouping label for the palette (e.g. core, integration)
	Category *string `json:"category,omitempty"`

	// ConfigSchema JSON Schema describing valid Node.config for this type
	ConfigSchema map[string]interface{} `json:"configSchema"`
	Description  *string                `json:"description,omitempty"`

	// Id Node type identifier (referenced by Node.type)
	Id string `json:"id"`

	// Name Human-readable name for the palette
	Name string `json:"name"`
}

// NodeTypeList defines model for NodeTypeList.
type NodeTypeList struct {
	NodeTypes []NodeType `json:"nodeTypes"`
}

// Position defines model for Position.
type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

// Run defines model for Run.
type Run struct {
	// CompletedAt Set when status is terminal (completed, failed, cancelled)
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// Error Error message when status is failed
	Error   *string            `json:"error,omitempty"`
	GraphId openapi_types.UUID `json:"graphId"`
	Id      openapi_types.UUID `json:"id"`

	// Result Workflow output when status is completed
	Result    *map[string]interface{} `json:"result,omitempty"`
	StartedAt time.Time               `json:"startedAt"`

	// Status Current lifecycle state of a workflow run
	Status RunStatus `json:"status"`
}

// RunStatus Current lifecycle state of a workflow run
type RunStatus string

// StartRunRequest defines model for StartRunRequest.
type StartRunRequest struct {
	// Input Optional input payload passed to the workflow
	Input *map[string]interface{} `json:"input,omitempty"`
}

// GraphId defines model for GraphId.
type GraphId = openapi_types.UUID

// RunId defines model for RunId.
type RunId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// CreateGraphJSONRequestBody defines body for CreateGraph for application/json ContentType.
type CreateGraphJSONRequestBody = CreateGraphRequest

// StartGraphRunJSONRequestBody defines body for StartGraphRun for application/json ContentType.
type StartGraphRunJSONRequestBody = StartRunRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateGraph Create a graph
	// (POST /graphs)
	CreateGraph(w http.ResponseWriter, r *http.Request)
	// GetGraph Fetch a graph by ID
	// (GET /graphs/{graphId})
	GetGraph(w http.ResponseWriter, r *http.Request, graphId GraphId)
	// StartGraphRun Start a workflow run from a graph
	// (POST /graphs/{graphId}/run)
	StartGraphRun(w http.ResponseWriter, r *http.Request, graphId GraphId)
	// ListNodeTypes List available node types
	// (GET /node-types)
	ListNodeTypes(w http.ResponseWriter, r *http.Request)
	// GetRun Poll run status and result
	// (GET /runs/{runId})
	GetRun(w http.ResponseWriter, r *http.Request, runId RunId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateGraph operation middleware
func (siw *ServerInterfaceWrapper) CreateGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "graphId" -------------
	var graphId GraphId

	err = runtime.BindStyledParameterWithOptions("simple", "graphId", r.PathValue("graphId"), &graphId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "graphId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r, graphId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartGraphRun operation middleware
func (siw *ServerInterfaceWrapper) StartGraphRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "graphId" -------------
	var graphId GraphId

	err = runtime.BindStyledParameterWithOptions("simple", "graphId", r.PathValue("graphId"), &graphId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "graphId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartGraphRun(w, r, graphId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodeTypes operation middleware
func (siw *ServerInterfaceWrapper) ListNodeTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodeTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/graphs", wrapper.CreateGraph)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/graphs/{graphId}", wrapper.GetGraph)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/graphs/{graphId}/run", wrapper.StartGraphRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{runId}", wrapper.GetRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/node-types", wrapper.ListNodeTypes)

	return m
}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type CreateGraphRequestObject struct {
	Body *CreateGraphJSONRequestBody
}

type CreateGraphResponseObject interface {
	VisitCreateGraphResponse(w http.ResponseWriter) error
}

type CreateGraph201JSONResponse Graph

func (response CreateGraph201JSONResponse) VisitCreateGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGraph400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateGraph400JSONResponse) VisitCreateGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGraph500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateGraph500JSONResponse) VisitCreateGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraphRequestObject struct {
	GraphId GraphId `json:"graphId"`
}

type GetGraphResponseObject interface {
	VisitGetGraphResponse(w http.ResponseWriter) error
}

type GetGraph200JSONResponse Graph

func (response GetGraph200JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraph404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGraph404JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraph500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetGraph500JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRunRequestObject struct {
	GraphId GraphId `json:"graphId"`
	Body    *StartGraphRunJSONRequestBody
}

type StartGraphRunResponseObject interface {
	VisitStartGraphRunResponse(w http.ResponseWriter) error
}

type StartGraphRun202JSONResponse Run

func (response StartGraphRun202JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRun404JSONResponse struct{ NotFoundJSONResponse }

func (response StartGraphRun404JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRun409JSONResponse Error

func (response StartGraphRun409JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StartGraphRun500JSONResponse struct{ InternalErrorJSONResponse }

func (response StartGraphRun500JSONResponse) VisitStartGraphRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListNodeTypesRequestObject struct {
}

type ListNodeTypesResponseObject interface {
	VisitListNodeTypesResponse(w http.ResponseWriter) error
}

type ListNodeTypes200JSONResponse NodeTypeList

func (response ListNodeTypes200JSONResponse) VisitListNodeTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNodeTypes400JSONResponse struct{ BadRequestJSONResponse }

func (response ListNodeTypes400JSONResponse) VisitListNodeTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListNodeTypes500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListNodeTypes500JSONResponse) VisitListNodeTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRunRequestObject struct {
	RunId RunId `json:"runId"`
}

type GetRunResponseObject interface {
	VisitGetRunResponse(w http.ResponseWriter) error
}

type GetRun200JSONResponse Run

func (response GetRun200JSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRun404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRun404JSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRun500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetRun500JSONResponse) VisitGetRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateGraph Create a graph
	// (POST /graphs)
	CreateGraph(ctx context.Context, request CreateGraphRequestObject) (CreateGraphResponseObject, error)
	// GetGraph Fetch a graph by ID
	// (GET /graphs/{graphId})
	GetGraph(ctx context.Context, request GetGraphRequestObject) (GetGraphResponseObject, error)
	// StartGraphRun Start a workflow run from a graph
	// (POST /graphs/{graphId}/run)
	StartGraphRun(ctx context.Context, request StartGraphRunRequestObject) (StartGraphRunResponseObject, error)
	// ListNodeTypes List available node types
	// (GET /node-types)
	ListNodeTypes(ctx context.Context, request ListNodeTypesRequestObject) (ListNodeTypesResponseObject, error)
	// GetRun Poll run status and result
	// (GET /runs/{runId})
	GetRun(ctx context.Context, request GetRunRequestObject) (GetRunResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateGraph operation middleware
func (sh *strictHandler) CreateGraph(w http.ResponseWriter, r *http.Request) {
	var request CreateGraphRequestObject

	var body CreateGraphJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGraph(ctx, request.(CreateGraphRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGraph")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGraphResponseObject); ok {
		if err := validResponse.VisitCreateGraphResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGraph operation middleware
func (sh *strictHandler) GetGraph(w http.ResponseWriter, r *http.Request, graphId GraphId) {
	var request GetGraphRequestObject

	request.GraphId = graphId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGraph(ctx, request.(GetGraphRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGraph")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGraphResponseObject); ok {
		if err := validResponse.VisitGetGraphResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartGraphRun operation middleware
func (sh *strictHandler) StartGraphRun(w http.ResponseWriter, r *http.Request, graphId GraphId) {
	var request StartGraphRunRequestObject

	request.GraphId = graphId

	var body StartGraphRunJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartGraphRun(ctx, request.(StartGraphRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartGraphRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartGraphRunResponseObject); ok {
		if err := validResponse.VisitStartGraphRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNodeTypes operation middleware
func (sh *strictHandler) ListNodeTypes(w http.ResponseWriter, r *http.Request) {
	var request ListNodeTypesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListNodeTypes(ctx, request.(ListNodeTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNodeTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListNodeTypesResponseObject); ok {
		if err := validResponse.VisitListNodeTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRun operation middleware
func (sh *strictHandler) GetRun(w http.ResponseWriter, r *http.Request, runId RunId) {
	var request GetRunRequestObject

	request.RunId = runId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRun(ctx, request.(GetRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRun")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRunResponseObject); ok {
		if err := validResponse.VisitGetRunResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
